### ISSUE TITLE
Style weas animation control input

### ISSUE THREAD

**Issue by eimrek** [materialscloud-org/interactive-phonon-visualizer#8]
The weas animation control buttons and progressbar currently have a default html button style that doesn't match the rest of the app.

Could we use similar style buttons there as for the "Settings" panel?

One option is that weas exposes the styling control of these somehow (e.g. by a css class) or alternatively, these input controls could be implemented with bootstrap buttons in this repo, and weas could expose a callback function for playing and pausing the animation.

@superstar54

**Comment by superstar54** [comment]
Hi @eimrek , yes, weas can expose the API so that you can control the animation. I will update it.
